- name: Убедиться, что директория {{ redis.directory }} существует
  file:
    path: "{{ redis.directory }}"
    state: directory
    mode: '0755'

- name: Создать .env файл
  template:
    src: "env.j2"
    dest: "{{ redis.directory }}/.env"
    mode: '0600'

- name: Скопировать docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ redis.directory }}/docker-compose.yml"
    mode: "0644"
  notify: Положить docker-compose.yml