- import_playbook: "playbooks/wireguard.yml"
- import_playbook: "playbooks/docker.yml"
- import_playbook: "playbooks/postgres.yml"
- import_playbook: "playbooks/gitea.yml"
- import_playbook: "playbooks/traefik.yml"