servers:
  hosts:
    alma-server:
      ansible_host: '192.168.2.128'
      ansible_port: '2222'
      ansible_user: 'user'

local:
  hosts:
    localhost:
      ansible_connetion: local
      ansible_host: "127.0.0.1"
      ansible_user: user
      