apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBJq/GKT5FnBGcW3uOcc7gkxKVIg/XA91YyGUUt2p/V2wBqxVmZI0Hqn2JUyx54oKVLu8OIHbO8k2FCPlmhDq61gQF2Sh0NqA9lWhQzw+nF5WWHkKo68RLFAnxGgMrhos/bNUajLv0i2q40DIxThpcGVqBMGWD7mcBX2Og/ps08u4txzR9vxSC0UMlApHIW2N4Qzfk0UMBGQ2dcJxKx8Sb5vJzTUjGylhZYxl8N5aJyp9m3cWFje9d4hg+1qXOYh8M6gxN1cmfatB0C0OXyE6tpe84l7r9YlC9SfCKlT4DuChBtf0DD42KAUWL77ZfTm1Sw9skwsaNR65pLc4fP2/PmPyqcaoHGfPbbz4ZrwnsfPuA72nZkCcxo0AqQUUnZdky1rDtAmrx1uwrV7JQAjySzoFyJAtlYqqfD4SJOA24n9u1AwasjEmebRznK54imAfdVp+i1u0BcKR0QAZPJ5P6rqOqRn62r2Ia5jZGmk9YqO/dEeE4ah3k/PBnF0aSg+jjRxc0cHJzVo6mNulgr4Illp0TF7pDlh7x1ASlgvb4HKuxn3VDcWSBkmZzUkv7wDNViI3bU4hgk+HxTx/y1a6kzqDfbMS23xgCr2u1CQs/77pDqm+BEP3z3FXugN2Z542+orezm12Ume/cG88PhKpXDVZyB3Mo+5vfpBPWZseFOHfw9rlOBePvZmYPnKgl31KoYFsIRgITS6K9UIC4=
    admin-user: AgAOuTed6rsrAMo245f5Sq53UmDPxNmTqq2J76mPIA0SnQ7gEaBAQv1gUMpFTJ9a52qlZAqZyls/Unr8hPSazJSmdfQrJwNQe7d4GkjjglV39m5fttmCHLCJr8lvnjEG0ttR5Xh63XyyiOZlgQORjOeX1dyufjZUklyY/R9EjSFd3eA7oIkOHfh+ZJntFJdXcDWT4h+Sf4emZA59h9utC/0b+2F6kp9E2w44i6IyXK56IpYghkXUXjpoTT14w5L8TPBwLhrjoMaOZ2Y82Uf6y6lSLrv4jo402G8k7UaXK1ihrPNiP60AjH23WoVPXe8OSuRpl3HU06POdEr9XhiLhhRXretXu/DGyi/Fe3qclXNPStQhPnSYYdmmAEvQz61bhJL42bUiWY8dNIFPsLQ2y8lxlqAEpIcCZMrbVWMxXYI3c+P49iOUNbh9zOVDX2PPtwNj70RbyoNWQVz302ydomC0rG5qrBzUb+QCkImItx/5HvHgViN5oi8d9m54x2DUC6khZVTAPBE+Dtfktyx1wG4wWo8VVgNpgEQ8fxEx4aHPpQ8QLXMQuGAEFv9sEBBxfk2KFhCHKNcikhmnL/jnTcylQ7z3vpbUZHfBEMwZwBOkuKuanK9HA3qwEMPtspNz+HgLZJhsQoDEBAtTteOToRfQN7EmCF5bbjiJl8nZZe6rN62aHue40+yXawSgY2YenyHYD4jjaw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: monitoring
