---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mikrotik-credentials
  namespace: monitoring
spec:
  encryptedData:
    mktxp.conf: AgCZpsEIbnHT5eFnsHs7F2JWkEEvBt1DDoKabCYCQe5stJeeN7iMwf0eEGz1/veDCuVfGhHv8sQOrsB6kHycxJsixcnbcE7jv2b40iClI9SwhrHjqf1eHR3TnjYjYkt1Ic/xhy0dGUpx15dndSHUn99KIlit2tnB0cPW99jcK3W+Ur9Cw3K6hVBeSPTK0uLNADD9NP0gT9OEMLxbX/LBQyVmZEjbb/fuOoQuHHhu+i561Q1AX1tCWSedFvTCNwpEXT+jrCxvHoUhdCJ0yGJEcA0NziHvUlKd3RJblm+sRita/GfQXJrlFd96VouVz3zHeADhcVXg1u0egPi7j+ZazE9/iLGgT1DeZplQk9Nlq41+nS4x3iusju9mZjXpOZ7iYJmyqwQgZaX5WVfxwM4bWSuFjB+3pE/AyHZ+GPHz5IddeRIhaJIAnw7Hjz6P0ifmYhp2yiiDXxKiCDsgvOeXyGiMPy7dRJqJztjm1PckHYnSUtddbAsi3flhprmUK1AxjO8TIaoIjP7trf/bK2PyQDKI11Z3uQHUjPD+P/ptCVPMX7n4Jd42rlUnXpbnysu+A2MGYDP3wNHrbLOna0bXlwx/LfgcQdVzeThguig0VXNnu3QBsInifL6pGoWNo6dZQqOai3gzAa7jw1G+NBxvIQpdXb7U0CHVr8xcnTPxfxZd3NsfiTE++7szk+4mCT1i9ok/Q/SsJi1fyLeHF7t1eONTwmBwCcum1+X1L91tJgxb0xGdDRcA9YPaA1Ol8KpQl0drrkXC/p9yzpokEOaJ8Hi1kQaqppf0Ywj4Hgqdra76CXwAVonGVSMOKM5+6urh/a4HzYGG5ny4orJIMqID7rN9AKY1/c/HAmDQTVAJwXmQv2gKI525wLhEriHuUHQBnVR/r5kMcClUw9nHOBTBuID7RjPGUg9b9M+ZeNvnsqoGrcI4W/H0ltShV/s1VVTHIZ1ol5BEdbmWWAUpuHRAdfzsImRRkEjpJFqEDAIwS2rGH7JLRfdEOGjUciovtjB6Hdv409kEBaqDi9Dv2ju8mWDE9jPYAEOn40TWz3dWhz/eanTMwHuwHlbiP0Dhd67jwX4trYnZfLGZ3EoF0tB42bTpEvlHVvkpNV1ZwD5sV1uwO3CBXplLtuB02Qkfb/XJirnbMmgE+dh4H7m+WMqmK1NcYX9yR9krg0IZ6n5pepYrrcN1I283c+nvlIKVrlt2k1MJtLjkGDpZ4jPFaN0f+tKAoeDA0YWkctHM+9SX4g==
  template:
    metadata:
      creationTimestamp: null
      name: mikrotik-credentials
      namespace: monitoring
