apiVersion: v1
kind: ConfigMap
metadata:
  name: mikrotik-exporter-config
  namespace: monitoring
data:
  _mktxp.conf: |
    [MKTXP]
        port = 49090
        socket_timeout = 2
        initial_delay_on_connect = 1
        initial_delay_on_failure = 10
        max_delay_on_failure = 300
        delay_inc_div = 5
        bandwidth_test_interval = 0
        minimal_collect_interval = 5
        max_worker_threads = 5
        max_scrape_duration = 10
        total_max_scrape_duration = 30
        verbose_mode = True
        fetch_routers_in_parallel = False
        compact_default_conf_values = True
        persistent_router_connection_pool = False
        probe_connection_pool = False
        persistent_dhcp_cache = False
        prometheus_headers_deduplication = False
