apiVersion: v1
kind: ConfigMap
metadata:
  name: mikrotik-exporter-config
  namespace: monitoring
data:
  _mktxp.conf: |
    [MKTXP]
        port = 49090
        socket_timeout = 2
        initial_delay_on_connect = 1
        verbose_mode = False
        fetch_routers_in_parallel = False
        