gitlab:
  version: "latest"
  container_name: "gitlab"
  domain_name: "gitlab.{{ root_domain }}"
  port_http: "8929"
  port_internal_http: "8929"
  port_ssh: "22"
  port_internal_ssh: "22"
  directory: "/opt/gitlab"
  db_type: "postgresql"
  db_user: "gitlab"
  db_name: "gitlab"
  db_encoding: "utf8"
  db_host: "{{ docker_internal_net }}.{{ postgres.net_addr }}"
  redis_host: "{{ docker_internal_net }}.{{ redis.net_addr }}"