wg_path: "/etc/wireguard"
wg_server_private_key_path: "/etc/wireguard/privatekey"
wg_peers_path: "wireguard_peers"
wg_public_port: "51820"
wg_interface_address: "10.100.0.1/24"
wg_conf: "wg0.conf"
wg_conf_owner: "root"
wg_conf_owner_group: "root"
wg_daemon_name: "wg-quick@wg0"