- name: Создать директорию {{ traefik.directory }}
  file:
    path: "{{ traefik.directory }}"
    state: directory
    mode: "0744"

- name: Скопировать docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ traefik.directory }}/docker-compose.yml"
    mode: "0644"
  notify: Положить traefik docker-compose.yml

- meta: flush_handlers

- name: Запусить контейнер с Traefik
  command: "docker compose -f {{ traefik.directory }}/docker-compose.yml up -d"