- name: Установка зависимостей community.postgresql
  pip:
    name:
      - psycopg2-binary
    executable: "{{ pip_path }}"

- name: Убедиться, что пользователь базы данных существует
  community.postgresql.postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    state: present
    login_user: "{{ postgres.user }}"
    login_password: "{{ postgres_db_pass }}"
    login_host: "{{ docker_internal_net }}.{{ postgres.net_addr }}"
    login_port: "{{ postgres.internal_port }}"
  loop: "{{ db_list }}"

- name: Убедиться, что база данных существует
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.user }}"
    state: present
    login_user: "{{ postgres.user }}"
    login_password: "{{ postgres_db_pass }}"
    login_host: "{{ docker_internal_net }}.{{ postgres.net_addr }}"
    login_port: "{{ postgres.internal_port }}"
  loop: "{{ db_list }}"