- name: Положить контейнер если требуется
  include_tasks: deploy.yml
  when: compose_action == "down"

- name: Поднять контейнер если требуется
  include_tasks: run.yml
  when: compose_action == "up"

- name: Создать базы данных
  include_tasks: db_create.yml
  when: db_create | bool