- name: Сконфигурировать traefik и положить контейнер если требуется
  hosts: servers
  become: true
  roles:
    - role: traefik
      vars:
        compose_action: down

- name: Запустить контейнер
  hosts: servers
  become: true
  roles:
    - role: traefik
      vars:
        compose_action: up