- name: Установка Wireguard
  dnf:
    name: wireguard-tools
    state: present
    update_cache: true

- name: Включить IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Создать {{ wg_path }}
  file:
    path: "{{ wg_path }}"
    state: directory
    mode: "0700"

- name: Скопировать конфигурацию сервера {{ wg_path }}/{{ wg_conf }}
  template:
    src: "{{ wg_conf }}.j2"
    dest: "{{ wg_path }}/{{ wg_conf }}"
    owner: "{{ wg_conf_owner }}"
    group: "{{ wg_conf_owner_group }}"
    mode: "0600"

- name: Включить и запустить {{ wg_daemon_name }}
  systemd:
    name: "{{ wg_daemon_name }}"
    enabled: true
    state: started

- name: Открыть порт {{ wg_firewall_port }} в firewalld
  ansible.posix.firewalld:
    port: "{{ wg_firewall_port }}"
    permanent: yes
    state: enabled
    immediate: yes
